AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSecretsID:
    Type: String
    Description: The ID of the Secrets Manager secret containing the RDS database credentials.

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        DB_SECRETS_ID: !Ref DBSecretsID
        DB_NAME: 'inventory'

Resources:
  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email

  # Lambda Functions
  GetStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/
      Handler: getStock.handler
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DBSecretsID}
      Events:
        GetStock:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /material/stock
            Method: get

  UpdateStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/
      Handler: updateStock.handler
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DBSecretsID}
      Events:
        UpdateStock:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /material/{material_id}/stock
            Method: patch

Outputs:
  ApiEndpoint:
    Description: "API Gateway 端点"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
    
  UserPoolId:
    Description: "Cognito 用户池 ID"
    Value: !Ref UserPool