AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSecretsID:
    Type: String
    Description: The ID of the Secrets Manager secret containing the RDS database credentials.
  EmailIdentity:
    Type: String
    Description: The email identity for sending emails using SES.
  VpcSecurityGroupId:
    Type: String
    Description: The ID of the security group for Lambda functions.
  VpcSubnet1:
    Type: String
    Description: The ID of the first subnet for Lambda functions.
  VpcSubnet2:
    Type: String
    Description: The ID of the second subnet for Lambda functions.

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        DB_SECRETS_ID: !Ref DBSecretsID
        DB_NAME: 'inventory'
        SES_FROM_ADDRESS: !Ref EmailIdentity
    VpcConfig:
      SecurityGroupIds:
        - !Ref VpcSecurityGroupId
      SubnetIds:
        - !Ref VpcSubnet1
        - !Ref VpcSubnet2

Resources:
  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, PATCH, DELETE, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: "{\"error\":\"Unauthorized\"}"
        AUTHORIZER_FAILURE:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: "{\"error\":\"Auth Failed\"}"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email

  # Lambda Functions
  GetStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/getStock
      Handler: app.handler
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "*"
      Events:
        GetStock:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Auth:
              Authorizer: CognitoAuthorizer
            Path: /material/stock
            Method: get

  UpdateStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/updateStock
      Handler: app.handler
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "*"
      Events:
        UpdateStock:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Auth:
              Authorizer: CognitoAuthorizer
            Path: /material/{material_id}/stock
            Method: patch

  AlertStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/alertStock
      Handler: app.handler
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "*"
        - SESCrudPolicy:
            IdentityName: !Ref EmailIdentity
      Events:
        AlertShop1:
          Type: Schedule
          Properties:
            Schedule: cron(10 7 * * ? *)
            Input: '{"shopID": 1, "alertEmails": "chenye94@qq.com"}'

Outputs:
  ApiEndpoint:
    Description: "API Gateway 端点"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
    
  UserPoolId:
    Description: "Cognito 用户池 ID"
    Value: !Ref UserPool